name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    - name: set up JDK 11
      uses: actions/setup-java@main
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: sh gradlew build
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@main
      with:
        path: app/build/outputs/apk

    - name: Upload to Releases
      uses: svenstaro/upload-release-action@v2
      with:
        overwrite: true
        tag: ${{ github.ref }}
        release_name: Build CI
        asset_name: app-release-unsigned.apk
        repo_token: ${{ secrets.ACCESS_TOKEN }}
        body: "Automated release issued by Actions."
        file: app/build/outputs/apk/release/app-release-unsigned.apk
